const KEYWORDS = [
{"keyword": "지능", "english": "Intelligence", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "intelligence", "summary": "Cambridge 사전: ability to learn, understand, and make judgments or have opinions based on reason.", "week": 1},
{"keyword": "지능 정의", "english": "Definition of Intelligence", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "intelligence-definition", "summary": "Learn / Understand / Make judgments / Have opinions", "week": 1},
{"keyword": "용호 사례", "english": "Yongho the Dog", "category": "예시", "file": "01주차/01주차_학습서.html", "anchor": "yongho-case", "summary": "강아지가 적당한 크기 돌을 학습한 사례", "week": 1},
{"keyword": "인공", "english": "Artificial", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "artificial", "summary": "자연을 모방하여 사람이 만든 것", "week": 1},
{"keyword": "인공 정의", "english": "Definition of Artificial", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "artificial-definition", "summary": "Made by people, often as a copy of something natural", "week": 1},
{"keyword": "인공지능", "english": "Artificial Intelligence (AI)", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "ai-three-meanings", "summary": "맥락에 따라 학문/기술/시스템 세 가지 의미", "week": 1},
{"keyword": "지능적 시스템 4능력", "english": "Four Abilities of Intelligent System", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "intelligent-system-abilities", "summary": "언어 이해 / 그림 인식 / 문제 해결 / 학습", "week": 1},
{"keyword": "톰 미첼", "english": "Tom M. Mitchell", "category": "인물", "file": "01주차/01주차_학습서.html", "anchor": "mitchell", "summary": "기계학습의 형식적 정의. E·T·P", "week": 1},
{"keyword": "ETP", "english": "Experience, Task, Performance", "category": "정의", "file": "01주차/01주차_학습서.html", "anchor": "etp", "summary": "톰 미첼의 학습 정의", "week": 1},
{"keyword": "딱딱함과 부드러움", "english": "Hard vs Soft", "category": "비교", "file": "01주차/01주차_학습서.html", "anchor": "hard-soft", "summary": "How many vs How much, 이산 vs 연속, 좌뇌 vs 우뇌", "week": 1},
{"keyword": "허먼 두뇌우성 모델", "english": "Herrmann Brain Dominance (HBDI)", "category": "모델", "file": "01주차/01주차_학습서.html", "anchor": "hbdi", "summary": "뇌의 4영역(A·B·C·D)", "week": 1},
{"keyword": "삼위일체 뇌", "english": "Triune Brain", "category": "모델", "file": "01주차/01주차_학습서.html", "anchor": "triune-brain", "summary": "파충류의 뇌 → 변연계 → 신피질", "week": 1},
{"keyword": "AI는 인문학", "english": "AI as Humanities", "category": "주장", "file": "01주차/01주차_학습서.html", "anchor": "ai-humanities", "summary": "사람을 모르고 사람 같은 것을 만들 수 없다", "week": 1},
{"keyword": "튜링 테스트", "english": "Turing Test", "category": "이론", "file": "02주차/02주차_학습서.html", "anchor": "turing-test", "summary": "1950, Alan Turing. 이미테이션 게임", "week": 2},
{"keyword": "앨런 튜링", "english": "Alan Turing", "category": "인물", "file": "02주차/02주차_학습서.html", "anchor": "turing-test", "summary": "1950년 튜링 테스트 제안. 영국 수학자", "week": 2},
{"keyword": "이미테이션 게임", "english": "Imitation Game", "category": "이론", "file": "02주차/02주차_학습서.html", "anchor": "turing-test", "summary": "튜링 테스트의 다른 이름", "week": 2},
{"keyword": "중국어 방", "english": "Chinese Room", "category": "이론", "file": "02주차/02주차_학습서.html", "anchor": "chinese-room", "summary": "1980, John Searle. 튜링 테스트 통과해도 이해는 아님", "week": 2},
{"keyword": "존 썰", "english": "John Searle", "category": "인물", "file": "02주차/02주차_학습서.html", "anchor": "chinese-room", "summary": "1980년 중국어 방 사고실험", "week": 2},
{"keyword": "시스템 응답", "english": "System Response", "category": "이론", "file": "02주차/02주차_학습서.html", "anchor": "system-response", "summary": "시스템 전체가 이해한 것이다", "week": 2},
{"keyword": "AI 논쟁", "english": "AI Debate", "category": "흐름", "file": "02주차/02주차_학습서.html", "anchor": "ai-debate", "summary": "튜링 → 중국어 방 → 시스템 응답", "week": 2},
{"keyword": "다트머스 회의", "english": "Dartmouth Conference", "category": "사건", "file": "02주차/02주차_학습서.html", "anchor": "dartmouth", "summary": "1956, AI 용어 탄생", "week": 2},
{"keyword": "AI 겨울", "english": "AI Winter", "category": "사건", "file": "02주차/02주차_학습서.html", "anchor": "ai-winter", "summary": "두 번의 침체기", "week": 2},
{"keyword": "기호주의", "english": "Symbolism", "category": "접근법", "file": "02주차/02주차_학습서.html", "anchor": "symbolism-connectionism", "summary": "논리·기호 처리. scikit-learn 계열", "week": 2},
{"keyword": "연결주의", "english": "Connectionism", "category": "접근법", "file": "02주차/02주차_학습서.html", "anchor": "symbolism-connectionism", "summary": "신경망. Keras·딥러닝 계열", "week": 2},
{"keyword": "AGI", "english": "Artificial General Intelligence", "category": "수준", "file": "02주차/02주차_학습서.html", "anchor": "ai-levels", "summary": "일반 인공지능", "week": 2},
{"keyword": "ASI", "english": "Artificial Super Intelligence", "category": "수준", "file": "02주차/02주차_학습서.html", "anchor": "ai-levels", "summary": "초 인공지능", "week": 2},
{"keyword": "ANI", "english": "Artificial Narrow Intelligence", "category": "수준", "file": "02주차/02주차_학습서.html", "anchor": "ai-levels", "summary": "약 인공지능", "week": 2},
{"keyword": "알파고", "english": "AlphaGo", "category": "시스템", "file": "02주차/02주차_학습서.html", "anchor": "alphago", "summary": "MCTS + CNN + 강화학습", "week": 2},
{"keyword": "MCTS", "english": "Monte Carlo Tree Search", "category": "알고리즘", "file": "02주차/02주차_학습서.html", "anchor": "alphago", "summary": "몬테카를로 트리 탐색", "week": 2},
{"keyword": "이세돌", "english": "Lee Sedol", "category": "인물", "file": "02주차/02주차_학습서.html", "anchor": "system-response", "summary": "2016 알파고에 1승4패", "week": 2},
{"keyword": "상태공간 탐색", "english": "State Space Search", "category": "이론", "file": "03주차/03주차_학습서.html", "anchor": "state-space-search", "summary": "초기상태/목적상태/연산자 3요소", "week": 3},
{"keyword": "초기상태", "english": "Initial State", "category": "정의", "file": "03주차/03주차_학습서.html", "anchor": "state-space-search", "summary": "문제를 시작하는 상태", "week": 3},
{"keyword": "목적상태", "english": "Goal State", "category": "정의", "file": "03주차/03주차_학습서.html", "anchor": "state-space-search", "summary": "도달하고자 하는 상태", "week": 3},
{"keyword": "연산자", "english": "Operator", "category": "정의", "file": "03주차/03주차_학습서.html", "anchor": "state-space-search", "summary": "한 상태에서 다른 상태로 옮기는 행동", "week": 3},
{"keyword": "4가지 대표 문제", "english": "Four Classic Problems", "category": "예시", "file": "03주차/03주차_학습서.html", "anchor": "four-problems", "summary": "미로/8-퍼즐/틱택토/선교사와 식인종", "week": 3},
{"keyword": "선교사와 식인종", "english": "Missionaries and Cannibals", "category": "문제", "file": "03주차/03주차_학습서.html", "anchor": "four-problems", "summary": "(선교사수, 식인종수, 배위치)", "week": 3},
{"keyword": "8-퍼즐", "english": "8-Puzzle", "category": "문제", "file": "03주차/03주차_학습서.html", "anchor": "four-problems", "summary": "3×3 빈칸 + 1~8 숫자판", "week": 3},
{"keyword": "탐색 트리", "english": "Search Tree", "category": "자료구조", "file": "03주차/03주차_학습서.html", "anchor": "search-tree", "summary": "상태공간 탐색의 나무 표현", "week": 3},
{"keyword": "맹목적 탐색", "english": "Blind Search", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "blind-search", "summary": "눈 감고 문고리 잡기", "week": 3},
{"keyword": "BFS", "english": "Breadth-First Search", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "blind-search", "summary": "너비우선 탐색 - 큐", "week": 3},
{"keyword": "DFS", "english": "Depth-First Search", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "blind-search", "summary": "깊이우선 탐색 - 스택/재귀", "week": 3},
{"keyword": "휴리스틱", "english": "Heuristic", "category": "정의", "file": "03주차/03주차_학습서.html", "anchor": "a-star", "summary": "경험적 어림짐작 함수", "week": 3},
{"keyword": "A* 알고리즘", "english": "A-star Algorithm", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "a-star", "summary": "f(n) = g(n) + h(n)", "week": 3},
{"keyword": "게임 트리", "english": "Game Tree", "category": "자료구조", "file": "03주차/03주차_학습서.html", "anchor": "game-tree", "summary": "교대 게임의 탐색 트리", "week": 3},
{"keyword": "Min-Max 전략", "english": "Minimax Strategy", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "minmax", "summary": "나=Max(OR), 상대=Min(AND)", "week": 3},
{"keyword": "αβ 가지치기", "english": "Alpha-Beta Pruning", "category": "알고리즘", "file": "03주차/03주차_학습서.html", "anchor": "ab-pruning", "summary": "α=선수 최소이익, β=후수 최대이익", "week": 3},
{"keyword": "지식", "english": "Knowledge", "category": "정의", "file": "04주차/04주차_학습서.html", "anchor": "knowledge", "summary": "체계적으로 잘 조직된 정보 덩어리", "week": 4},
{"keyword": "지식 표현", "english": "Knowledge Representation", "category": "정의", "file": "04주차/04주차_학습서.html", "anchor": "knowledge-representation", "summary": "지식을 컴퓨터가 처리할 수 있는 형태로 표현", "week": 4},
{"keyword": "의미망", "english": "Semantic Net", "category": "지식표현", "file": "04주차/04주차_학습서.html", "anchor": "semantic-net", "summary": "그래프 형태로 지식 표현", "week": 4},
{"keyword": "규칙 기반", "english": "Rule-Based", "category": "지식표현", "file": "04주차/04주차_학습서.html", "anchor": "rule-based", "summary": "IF P THEN Q 형식", "week": 4},
{"keyword": "지식 병목", "english": "Knowledge Bottleneck", "category": "현상", "file": "04주차/04주차_학습서.html", "anchor": "knowledge-bottleneck", "summary": "사람의 지식 양이 너무 방대해 처리 불가", "week": 4},
{"keyword": "전문가 시스템", "english": "Expert System", "category": "시스템", "file": "04주차/04주차_학습서.html", "anchor": "expert-system", "summary": "특정 분야 전문가처럼 작동하는 AI. 5대 구성", "week": 4},
{"keyword": "추론 엔진", "english": "Inference Engine", "category": "구성요소", "file": "04주차/04주차_학습서.html", "anchor": "expert-system", "summary": "사실과 규칙을 결합해 결론 도출", "week": 4},
{"keyword": "설명 기능", "english": "Explanation Facility", "category": "구성요소", "file": "04주차/04주차_학습서.html", "anchor": "explanation", "summary": "전문가 시스템의 강점. 결론 근거 설명", "week": 4},
{"keyword": "XAI", "english": "Explainable AI", "category": "연구분야", "file": "04주차/04주차_학습서.html", "anchor": "xai", "summary": "설명 가능한 인공지능", "week": 4},
{"keyword": "뉴런", "english": "Neuron", "category": "생물학", "file": "04주차/04주차_학습서.html", "anchor": "neuron", "summary": "신경세포. 사람 뇌에 100억~1000억 개", "week": 4},
{"keyword": "수상돌기", "english": "Dendrite", "category": "뉴런 부위", "file": "04주차/04주차_학습서.html", "anchor": "neuron", "summary": "뉴런의 입력을 받는 부분", "week": 4},
{"keyword": "축색돌기", "english": "Axon", "category": "뉴런 부위", "file": "04주차/04주차_학습서.html", "anchor": "neuron", "summary": "뉴런의 출력을 내보내는 부분", "week": 4},
{"keyword": "시냅스", "english": "Synapse", "category": "뉴런 부위", "file": "04주차/04주차_학습서.html", "anchor": "synapse-learning", "summary": "뉴런 간 접합부. 학습의 본질", "week": 4},
{"keyword": "인공 뉴런", "english": "Artificial Neuron", "category": "모델", "file": "05주차/05주차_학습서.html", "anchor": "artificial-neuron", "summary": "생물학적 뉴런 단순화 계산 모델. n:1", "week": 5},
{"keyword": "가중치", "english": "Weight (W)", "category": "매개변수", "file": "05주차/05주차_학습서.html", "anchor": "weight", "summary": "시냅스에 해당. 학습=가중치 조정", "week": 5},
{"keyword": "가중치 합", "english": "Weighted Sum", "category": "계산", "file": "05주차/05주차_학습서.html", "anchor": "weight", "summary": "Σ Wᵢ·Xᵢ", "week": 5},
{"keyword": "활성함수", "english": "Activation Function", "category": "함수", "file": "05주차/05주차_학습서.html", "anchor": "activation", "summary": "비선형 변환 함수", "week": 5},
{"keyword": "계단함수", "english": "Step Function", "category": "활성함수", "file": "05주차/05주차_학습서.html", "anchor": "step-fn", "summary": "x≥0이면 1, 아니면 0", "week": 5},
{"keyword": "시그모이드", "english": "Sigmoid", "category": "활성함수", "file": "05주차/05주차_학습서.html", "anchor": "sigmoid", "summary": "1/(1+e⁻ˣ). 출력 (0,1)", "week": 5},
{"keyword": "ReLU", "english": "Rectified Linear Unit", "category": "활성함수", "file": "05주차/05주차_학습서.html", "anchor": "relu", "summary": "max(0,x). 딥러닝 표준", "week": 5},
{"keyword": "바이어스", "english": "Bias", "category": "구조", "file": "05주차/05주차_학습서.html", "anchor": "bias", "summary": "고정값 추가 입력. 학습 필수", "week": 5},
{"keyword": "다층 신경망", "english": "Multi-Layer Neural Network", "category": "구조", "file": "05주차/05주차_학습서.html", "anchor": "mlnn", "summary": "입력층 - 중간층 - 출력층", "week": 5},
{"keyword": "입력층", "english": "Input Layer", "category": "층", "file": "05주차/05주차_학습서.html", "anchor": "mlnn", "summary": "헛개비. 가중치 없음", "week": 5},
{"keyword": "은닉층", "english": "Hidden Layer", "category": "층", "file": "05주차/05주차_학습서.html", "anchor": "mlnn", "summary": "중간층. 1개 이상", "week": 5},
{"keyword": "전진 전파", "english": "Feed Forward", "category": "규칙", "file": "05주차/05주차_학습서.html", "anchor": "feed-forward", "summary": "한 층 → 다음 층 방향", "week": 5},
{"keyword": "완전 연결", "english": "Fully Connected", "category": "규칙", "file": "05주차/05주차_학습서.html", "anchor": "feed-forward", "summary": "다음 층 모든 뉴런으로 전달", "week": 5},
{"keyword": "오일러 상수", "english": "Euler's Number (e)", "category": "수학", "file": "05주차/05주차_학습서.html", "anchor": "sigmoid", "summary": "e ≈ 2.71828", "week": 5},
{"keyword": "매개변수", "english": "Parameter", "category": "용어", "file": "05주차/05주차_학습서.html", "anchor": "weight", "summary": "신경망의 가중치 수", "week": 5},
{"keyword": "신경망 학습", "english": "Neural Network Learning", "category": "정의", "file": "06주차/06주차_학습서.html", "anchor": "nn-learning", "summary": "가중치 수정 = 시냅스 강도 조절", "week": 6},
{"keyword": "오차", "english": "Error", "category": "정의", "file": "06주차/06주차_학습서.html", "anchor": "loss-function", "summary": "원하는 값 − 실제 출력", "week": 6},
{"keyword": "손실 함수", "english": "Loss Function", "category": "함수", "file": "06주차/06주차_학습서.html", "anchor": "loss-function", "summary": "비용=오차=손실 함수", "week": 6},
{"keyword": "경사하강법", "english": "Gradient Descent", "category": "알고리즘", "file": "06주차/06주차_학습서.html", "anchor": "gradient-descent", "summary": "ΔW = −α·(∂E/∂W)", "week": 6},
{"keyword": "학습률", "english": "Learning Rate", "category": "하이퍼파라미터", "file": "06주차/06주차_학습서.html", "anchor": "learning-rate", "summary": "α. 작은 양수", "week": 6},
{"keyword": "XOR 문제", "english": "XOR Problem", "category": "문제", "file": "06주차/06주차_학습서.html", "anchor": "xor-problem", "summary": "선형 분리 불가능", "week": 6},
{"keyword": "민스키와 페퍼트", "english": "Minsky & Papert", "category": "인물", "file": "06주차/06주차_학습서.html", "anchor": "xor-problem", "summary": "1969년 Perceptrons. AI 1차 겨울 야기", "week": 6},
{"keyword": "역전파", "english": "Backpropagation", "category": "알고리즘", "file": "06주차/06주차_학습서.html", "anchor": "backpropagation", "summary": "1986 Rumelhart, Hinton, Williams", "week": 6},
{"keyword": "연쇄 법칙", "english": "Chain Rule", "category": "수학", "file": "06주차/06주차_학습서.html", "anchor": "backpropagation", "summary": "역전파의 수학적 토대", "week": 6},
{"keyword": "하이퍼파라미터", "english": "Hyperparameter", "category": "용어", "file": "06주차/06주차_학습서.html", "anchor": "hyperparameter", "summary": "사람이 설정. 학습률·층수·뉴런수", "week": 6},
{"keyword": "에폭", "english": "Epoch", "category": "하이퍼파라미터", "file": "06주차/06주차_학습서.html", "anchor": "hyperparameter", "summary": "전체 데이터로 학습 한 바퀴", "week": 6},
{"keyword": "과적합", "english": "Overfitting", "category": "현상", "file": "06주차/06주차_학습서.html", "anchor": "overfitting", "summary": "새 데이터에 일반화 안 됨", "week": 6},
{"keyword": "과소적합", "english": "Underfitting", "category": "현상", "file": "06주차/06주차_학습서.html", "anchor": "overfitting", "summary": "모델이 너무 단순", "week": 6},
{"keyword": "정규화", "english": "Regularization", "category": "기법", "file": "06주차/06주차_학습서.html", "anchor": "overfitting", "summary": "과적합 방지", "week": 6},
{"keyword": "선형 분리 불가능", "english": "Non-linearly Separable", "category": "개념", "file": "06주차/06주차_학습서.html", "anchor": "xor-problem", "summary": "하나의 직선으로 분리 불가", "week": 6},
{"keyword": "신경망 응용", "english": "NN Application", "category": "정의", "file": "07주차/07주차_학습서.html", "anchor": "nn-application", "summary": "관계를 찾는 일", "week": 7},
{"keyword": "딥뉴럴 네트워크", "english": "Deep Neural Network (DNN)", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "dnn", "summary": "중간층 4개 이상의 깊은 신경망", "week": 7},
{"keyword": "딥러닝", "english": "Deep Learning", "category": "분야", "file": "07주차/07주차_학습서.html", "anchor": "dnn", "summary": "DNN 학습 기술 총칭", "week": 7},
{"keyword": "기울기 소실", "english": "Vanishing Gradient", "category": "문제", "file": "07주차/07주차_학습서.html", "anchor": "vanishing-gradient", "summary": "깊은 층 기울기가 0에 가까워짐", "week": 7},
{"keyword": "드롭아웃", "english": "Dropout", "category": "기법", "file": "07주차/07주차_학습서.html", "anchor": "dropout-tech", "summary": "뉴런 무작위 비활성화. 힌튼", "week": 7},
{"keyword": "CNN", "english": "Convolutional Neural Network", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "cnn", "summary": "합성곱 신경망. 이미지 처리", "week": 7},
{"keyword": "합성곱", "english": "Convolution", "category": "연산", "file": "07주차/07주차_학습서.html", "anchor": "cnn", "summary": "필터로 슬라이딩하며 특징 추출", "week": 7},
{"keyword": "풀링", "english": "Pooling", "category": "연산", "file": "07주차/07주차_학습서.html", "anchor": "cnn", "summary": "특징지도 크기 축소", "week": 7},
{"keyword": "RNN", "english": "Recurrent Neural Network", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "rnn", "summary": "순환 신경망. 시계열·언어", "week": 7},
{"keyword": "LSTM", "english": "Long Short-Term Memory", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "rnn", "summary": "RNN 변형. 장기 의존성", "week": 7},
{"keyword": "호필드 네트워크", "english": "Hopfield Network", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "rnn", "summary": "1982. 연관 기억", "week": 7},
{"keyword": "GPT", "english": "Generative Pre-trained Transformer", "category": "모델", "file": "07주차/07주차_학습서.html", "anchor": "gpt", "summary": "OpenAI. 트랜스포머 기반", "week": 7},
{"keyword": "트랜스포머", "english": "Transformer", "category": "구조", "file": "07주차/07주차_학습서.html", "anchor": "transformer", "summary": "2017 Google. 어텐션 기반", "week": 7},
{"keyword": "어텐션", "english": "Attention", "category": "메커니즘", "file": "07주차/07주차_학습서.html", "anchor": "attention", "summary": "입력의 어느 부분에 집중할지", "week": 7},
{"keyword": "GAN", "english": "Generative Adversarial Network", "category": "모델", "file": "07주차/07주차_학습서.html", "anchor": "gan", "summary": "생성적 적대 신경망", "week": 7},
{"keyword": "제프리 힌튼", "english": "Geoffrey Hinton", "category": "인물", "file": "07주차/07주차_학습서.html", "anchor": "hinton", "summary": "2024 노벨 물리학상", "week": 7},
{"keyword": "존 호필드", "english": "John Hopfield", "category": "인물", "file": "07주차/07주차_학습서.html", "anchor": "hopfield", "summary": "2024 노벨 물리학상", "week": 7},
{"keyword": "데미스 하사비스", "english": "Demis Hassabis", "category": "인물", "file": "07주차/07주차_학습서.html", "anchor": "hassabis", "summary": "2024 노벨 화학상. 알파폴드", "week": 7},
{"keyword": "알파폴드", "english": "AlphaFold", "category": "시스템", "file": "07주차/07주차_학습서.html", "anchor": "hassabis", "summary": "단백질 3D 구조 예측", "week": 7},
{"keyword": "확률", "english": "Probability", "category": "정의", "file": "08주차/08주차_학습서.html", "anchor": "probability", "summary": "불확실성을 0~1로 측정", "week": 8},
{"keyword": "조건부 확률", "english": "Conditional Probability", "category": "정의", "file": "08주차/08주차_학습서.html", "anchor": "conditional-prob", "summary": "P(A|X) = P(A∩X)/P(X)", "week": 8},
{"keyword": "베이즈 정리", "english": "Bayes' Theorem", "category": "정리", "file": "08주차/08주차_학습서.html", "anchor": "bayes", "summary": "결과로부터 원인을 추론", "week": 8},
{"keyword": "베이즈 규칙", "english": "Bayes' Rule", "category": "공식", "file": "08주차/08주차_학습서.html", "anchor": "bayes-formula", "summary": "P(A|X) = P(X|A)·P(A) / P(X)", "week": 8},
{"keyword": "사전확률", "english": "Prior Probability", "category": "용어", "file": "08주차/08주차_학습서.html", "anchor": "bayes", "summary": "증거 보기 전 원인의 초기 확률", "week": 8},
{"keyword": "우도", "english": "Likelihood", "category": "용어", "file": "08주차/08주차_학습서.html", "anchor": "bayes", "summary": "P(X|A)", "week": 8},
{"keyword": "사후확률", "english": "Posterior Probability", "category": "용어", "file": "08주차/08주차_학습서.html", "anchor": "bayes", "summary": "P(A|X). 갱신된 원인 확률", "week": 8},
{"keyword": "엄마는 고등어를 좋아해", "english": "Mom Likes Mackerel", "category": "사례", "file": "08주차/08주차_학습서.html", "anchor": "mom-mackerel", "summary": "베이즈 정리 적용 사례", "week": 8},
{"keyword": "암 진단 함정", "english": "Cancer Test Paradox", "category": "사례", "file": "08주차/08주차_학습서.html", "anchor": "cancer-test", "summary": "P(양성|암) != P(암|양성)", "week": 8},
{"keyword": "퍼지", "english": "Fuzzy", "category": "정의", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy", "summary": "1965 Lotfi Zadeh. 언어 모호함의 수학화", "week": 8},
{"keyword": "퍼지 집합", "english": "Fuzzy Set", "category": "정의", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy-set", "summary": "원소 소속 정도를 0~1로 표현", "week": 8},
{"keyword": "멤버십 함수", "english": "Membership Function", "category": "함수", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy-set", "summary": "μ_A(x) ∈ [0,1]", "week": 8},
{"keyword": "퍼지 추론", "english": "Fuzzy Inference", "category": "알고리즘", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy-inference", "summary": "4단계: 퍼지화→규칙→집계→비퍼지화", "week": 8},
{"keyword": "퍼지화", "english": "Fuzzification", "category": "단계", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy-inference", "summary": "수치를 멤버십 함수값으로", "week": 8},
{"keyword": "비퍼지화", "english": "Defuzzification", "category": "단계", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy-inference", "summary": "무게중심으로 수치 출력", "week": 8},
{"keyword": "Lotfi Zadeh", "english": "Lotfi Zadeh", "category": "인물", "file": "08주차/08주차_학습서.html", "anchor": "fuzzy", "summary": "1965년 퍼지 이론 제안", "week": 8},
{"keyword": "인터넷", "english": "Internet", "category": "정의", "file": "09주차/09주차_학습서.html", "anchor": "internet-vs-web", "summary": "TCP/IP 기반 글로벌 네트워크", "week": 9},
{"keyword": "월드와이드웹", "english": "World Wide Web", "category": "정의", "file": "09주차/09주차_학습서.html", "anchor": "internet-vs-web", "summary": "HTTP로 하이퍼텍스트 공유. 1989 팀 버너스리", "week": 9},
{"keyword": "TCP/IP", "english": "TCP/IP", "category": "프로토콜", "file": "09주차/09주차_학습서.html", "anchor": "internet-vs-web", "summary": "인터넷 표준 통신 규약", "week": 9},
{"keyword": "HTML", "english": "Hypertext Markup Language", "category": "언어", "file": "09주차/09주차_학습서.html", "anchor": "internet-vs-web", "summary": "웹페이지 작성 언어", "week": 9},
{"keyword": "웹 크롤러", "english": "Web Crawler", "category": "도구", "file": "09주차/09주차_학습서.html", "anchor": "crawler-indexing", "summary": "웹 문서 자동 수집", "week": 9},
{"keyword": "인덱싱", "english": "Indexing", "category": "기술", "file": "09주차/09주차_학습서.html", "anchor": "crawler-indexing", "summary": "단어 위치 사전 기록", "week": 9},
{"keyword": "페이지랭크", "english": "PageRank", "category": "알고리즘", "file": "09주차/09주차_학습서.html", "anchor": "pagerank", "summary": "1996 래리 페이지·세르게이 브린", "week": 9},
{"keyword": "래리 페이지", "english": "Larry Page", "category": "인물", "file": "09주차/09주차_학습서.html", "anchor": "pagerank", "summary": "구글 공동 창립자", "week": 9},
{"keyword": "빅데이터", "english": "Big Data", "category": "정의", "file": "09주차/09주차_학습서.html", "anchor": "big-data", "summary": "3V: Volume·Velocity·Variety", "week": 9},
{"keyword": "Volume", "english": "Volume", "category": "3V", "file": "09주차/09주차_학습서.html", "anchor": "volume", "summary": "용량", "week": 9},
{"keyword": "Velocity", "english": "Velocity", "category": "3V", "file": "09주차/09주차_학습서.html", "anchor": "velocity", "summary": "속도", "week": 9},
{"keyword": "Variety", "english": "Variety", "category": "3V", "file": "09주차/09주차_학습서.html", "anchor": "variety", "summary": "다양성", "week": 9},
{"keyword": "데이터 사이언스", "english": "Data Science", "category": "분야", "file": "09주차/09주차_학습서.html", "anchor": "big-data", "summary": "빅데이터에서 가치 추출", "week": 9},
{"keyword": "데이터 마이닝", "english": "Data Mining", "category": "기술", "file": "09주차/09주차_학습서.html", "anchor": "data-mining", "summary": "흙을 금으로 만드는 일", "week": 9},
{"keyword": "모두 거짓말을 한다", "english": "Everybody Lies", "category": "책", "file": "09주차/09주차_학습서.html", "anchor": "everybody-lies", "summary": "2017. 검색은 솔직", "week": 9},
{"keyword": "상관관계", "english": "Correlation", "category": "통계", "file": "09주차/09주차_학습서.html", "anchor": "correlation-causality", "summary": "두 변수가 함께 변함", "week": 9},
{"keyword": "인과관계", "english": "Causality", "category": "통계", "file": "09주차/09주차_학습서.html", "anchor": "correlation-causality", "summary": "한쪽이 다른 쪽의 원인", "week": 9},
{"keyword": "대량살상 수학무기", "english": "Weapons of Math Destruction", "category": "책", "file": "09주차/09주차_학습서.html", "anchor": "correlation-causality", "summary": "캐시 오닐", "week": 9},
{"keyword": "워드 클라우드", "english": "Word Cloud", "category": "기법", "file": "09주차/09주차_학습서.html", "anchor": "word-cloud", "summary": "단어 빈도 시각화", "week": 9},
{"keyword": "감성 분석", "english": "Sentiment Analysis", "category": "기법", "file": "09주차/09주차_학습서.html", "anchor": "sentiment", "summary": "텍스트 감정 수치화", "week": 9},
{"keyword": "Google NGram Viewer", "english": "Google NGram Viewer", "category": "도구", "file": "09주차/09주차_학습서.html", "anchor": "ngram", "summary": "책의 단어 빈도 시대별 그래프", "week": 9},
{"keyword": "머신러닝", "english": "Machine Learning (ML)", "category": "정의", "file": "10주차/10주차_학습서.html", "anchor": "ml", "summary": "AI ⊃ ML ⊃ NN ⊃ DL", "week": 10},
{"keyword": "지도학습", "english": "Supervised Learning", "category": "분류", "file": "10주차/10주차_학습서.html", "anchor": "supervised", "summary": "정답이 있는 학습", "week": 10},
{"keyword": "비지도학습", "english": "Unsupervised Learning", "category": "분류", "file": "10주차/10주차_학습서.html", "anchor": "clustering", "summary": "정답이 없는 학습", "week": 10},
{"keyword": "회귀", "english": "Regression", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "regression", "summary": "관계식 찾기. Y=mx+b", "week": 10},
{"keyword": "최소자승법", "english": "Least Squares", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "regression", "summary": "회귀의 전통적 방법", "week": 10},
{"keyword": "분류", "english": "Classification", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "classification", "summary": "어디에 속하는지 가려내기", "week": 10},
{"keyword": "햄", "english": "Ham", "category": "용어", "file": "10주차/10주차_학습서.html", "anchor": "classification", "summary": "정상 메일", "week": 10},
{"keyword": "군집화", "english": "Clustering", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "clustering", "summary": "덩어리 묶기. 비지도학습", "week": 10},
{"keyword": "k-Means", "english": "k-Means", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "kmeans", "summary": "K개 중심 → 가까운 데이터 → 무게중심 이동", "week": 10},
{"keyword": "계층적 알고리즘", "english": "Hierarchical Algorithm", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "kmeans", "summary": "가까운 것끼리 묶어가며 K 줄임", "week": 10},
{"keyword": "레이블링", "english": "Labeling", "category": "용어", "file": "10주차/10주차_학습서.html", "anchor": "clustering", "summary": "군집화 후 이름 붙이기", "week": 10},
{"keyword": "Scikit-learn", "english": "Scikit-learn", "category": "도구", "file": "10주차/10주차_학습서.html", "anchor": "ml", "summary": "기호주의 ML 라이브러리", "week": 10},
{"keyword": "추천 시스템", "english": "Recommendation System", "category": "시스템", "file": "10주차/10주차_학습서.html", "anchor": "recommendation", "summary": "사용자 기반 + 아이템 기반", "week": 10},
{"keyword": "협업 필터링", "english": "Collaborative Filtering", "category": "알고리즘", "file": "10주차/10주차_학습서.html", "anchor": "collab-filter", "summary": "유사성 측정이 시작이자 끝", "week": 10},
{"keyword": "유클리드 거리", "english": "Euclidean Distance", "category": "측정", "file": "10주차/10주차_학습서.html", "anchor": "collab-filter", "summary": "두 점 사이의 직선 거리", "week": 10},
{"keyword": "추천 점수", "english": "Recommendation Score", "category": "공식", "file": "10주차/10주차_학습서.html", "anchor": "collab-filter", "summary": "Σ(유사성×평점) / Σ유사성", "week": 10},
{"keyword": "자연 컴퓨팅", "english": "Natural Computing", "category": "정의", "file": "11주차/11주차_학습서.html", "anchor": "natural-computing", "summary": "3대 범주: 배우기/합성하기/사용하기", "week": 11},
{"keyword": "자연에서 배우기", "english": "Learning from Nature", "category": "범주", "file": "11주차/11주차_학습서.html", "anchor": "natural-computing", "summary": "신경망·GA·ACO·PSO", "week": 11},
{"keyword": "자연 합성하기", "english": "Synthesizing Nature", "category": "범주", "file": "11주차/11주차_학습서.html", "anchor": "natural-computing", "summary": "L-시스템, 가상 생명체", "week": 11},
{"keyword": "자연 사용하기", "english": "Using Nature", "category": "범주", "file": "11주차/11주차_학습서.html", "anchor": "natural-computing", "summary": "DNA 컴퓨팅, 양자 컴퓨팅", "week": 11},
{"keyword": "군집 지능", "english": "Swarm Intelligence", "category": "분야", "file": "11주차/11주차_학습서.html", "anchor": "nc-branches", "summary": "개미·꿀벌·새 떼 모방", "week": 11},
{"keyword": "PSO", "english": "Particle Swarm Optimization", "category": "알고리즘", "file": "11주차/11주차_학습서.html", "anchor": "pso", "summary": "입자 군집 최적화. 이웃 정보 활용", "week": 11},
{"keyword": "L-시스템", "english": "L-System", "category": "시스템", "file": "11주차/11주차_학습서.html", "anchor": "l-system", "summary": "린덴마이어. 식물 성장 프랙탈", "week": 11},
{"keyword": "프랙탈", "english": "Fractal", "category": "개념", "file": "11주차/11주차_학습서.html", "anchor": "l-system", "summary": "자기 유사 패턴", "week": 11},
{"keyword": "칼 심스", "english": "Karl Sims", "category": "인물", "file": "11주차/11주차_학습서.html", "anchor": "l-system", "summary": "1994 가상 생명체. NN+GA", "week": 11},
{"keyword": "DNA 컴퓨팅", "english": "DNA Computing", "category": "컴퓨팅", "file": "11주차/11주차_학습서.html", "anchor": "dna-quantum", "summary": "A·G·C·T 4진법", "week": 11},
{"keyword": "양자 컴퓨팅", "english": "Quantum Computing", "category": "컴퓨팅", "file": "11주차/11주차_학습서.html", "anchor": "dna-quantum", "summary": "양자 중첩 이용", "week": 11},
{"keyword": "큐비트", "english": "Qubit", "category": "단위", "file": "11주차/11주차_학습서.html", "anchor": "dna-quantum", "summary": "양자 컴퓨팅 기본 단위", "week": 11},
{"keyword": "슈뢰딩거의 고양이", "english": "Schrödinger's Cat", "category": "사고실험", "file": "11주차/11주차_학습서.html", "anchor": "dna-quantum", "summary": "양자 중첩 설명", "week": 11},
{"keyword": "개미 군집 최적화", "english": "Ant Colony Optimization (ACO)", "category": "알고리즘", "file": "11주차/11주차_학습서.html", "anchor": "aco", "summary": "페로몬+증발. α·β·ρ", "week": 11},
{"keyword": "페로몬", "english": "Pheromone", "category": "물질", "file": "11주차/11주차_학습서.html", "anchor": "aco", "summary": "개미가 길에 남기는 화학 신호", "week": 11},
{"keyword": "증발", "english": "Evaporation", "category": "현상", "file": "11주차/11주차_학습서.html", "anchor": "aco", "summary": "페로몬이 약해지는 현상", "week": 11},
{"keyword": "스티그머지", "english": "Stigmergy", "category": "개념", "file": "11주차/11주차_학습서.html", "anchor": "stigmergy", "summary": "환경 변화를 통한 간접 소통", "week": 11},
{"keyword": "TSP", "english": "Traveling Salesperson Problem", "category": "문제", "file": "11주차/11주차_학습서.html", "anchor": "aco", "summary": "외판원 문제. NP 문제", "week": 11},
{"keyword": "자기 조직화", "english": "Self-Organization", "category": "개념", "file": "11주차/11주차_학습서.html", "anchor": "self-org", "summary": "누가 지시하지 않아도 질서 형성", "week": 11},
{"keyword": "면역 컴퓨팅", "english": "Immune Computing", "category": "분야", "file": "11주차/11주차_학습서.html", "anchor": "nc-branches", "summary": "항원-항체 반응 모방", "week": 11},
{"keyword": "진화", "english": "Evolution", "category": "정의", "file": "12주차/12주차_학습서.html", "anchor": "evolution", "summary": "선택 + 유전", "week": 12},
{"keyword": "자연 선택", "english": "Natural Selection", "category": "진화 원리", "file": "12주차/12주차_학습서.html", "anchor": "evolution", "summary": "환경에 적합한 것이 살아남음", "week": 12},
{"keyword": "유전", "english": "Heredity", "category": "진화 원리", "file": "12주차/12주차_학습서.html", "anchor": "evolution", "summary": "형질이 자손에게 전해짐", "week": 12},
{"keyword": "유전 알고리즘", "english": "Genetic Algorithm (GA)", "category": "알고리즘", "file": "12주차/12주차_학습서.html", "anchor": "ga", "summary": "자연 진화에서 아이디어", "week": 12},
{"keyword": "인코딩", "english": "Encoding", "category": "GA 단계", "file": "12주차/12주차_학습서.html", "anchor": "encoding", "summary": "문제를 비트 수열로 표현", "week": 12},
{"keyword": "유전형", "english": "Genotype", "category": "용어", "file": "12주차/12주차_학습서.html", "anchor": "encoding", "summary": "DNA 표현. 비트 코드", "week": 12},
{"keyword": "표현형", "english": "Phenotype", "category": "용어", "file": "12주차/12주차_학습서.html", "anchor": "encoding", "summary": "발현된 실제 모습", "week": 12},
{"keyword": "모집단", "english": "Population", "category": "GA 단계", "file": "12주차/12주차_학습서.html", "anchor": "ga", "summary": "후보 해 집합", "week": 12},
{"keyword": "염색체", "english": "Chromosome", "category": "용어", "file": "12주차/12주차_학습서.html", "anchor": "encoding", "summary": "각 개체의 비트 수열", "week": 12},
{"keyword": "유전자", "english": "Gene", "category": "용어", "file": "12주차/12주차_학습서.html", "anchor": "encoding", "summary": "비트 하나하나", "week": 12},
{"keyword": "적합도", "english": "Fitness", "category": "용어", "file": "12주차/12주차_학습서.html", "anchor": "fitness", "summary": "개체의 적합 정도", "week": 12},
{"keyword": "적합도 함수", "english": "Fitness Function", "category": "함수", "file": "12주차/12주차_학습서.html", "anchor": "fitness", "summary": "비용=평가=적합도 함수", "week": 12},
{"keyword": "선택", "english": "Selection", "category": "GA 단계", "file": "12주차/12주차_학습서.html", "anchor": "selection", "summary": "다음 세대 부모 뽑기", "week": 12},
{"keyword": "룰렛휠 선택", "english": "Roulette Wheel Selection", "category": "선택 방식", "file": "12주차/12주차_학습서.html", "anchor": "selection", "summary": "적합도 비율로 무작위 추출", "week": 12},
{"keyword": "엘리티시즘", "english": "Elitism", "category": "선택 방식", "file": "12주차/12주차_학습서.html", "anchor": "selection", "summary": "상위 개체 무조건 선택", "week": 12},
{"keyword": "교차", "english": "Crossover", "category": "유전 연산", "file": "12주차/12주차_학습서.html", "anchor": "genetic-op", "summary": "개체 단위. 교차율 ~70%", "week": 12},
{"keyword": "돌연변이", "english": "Mutation", "category": "유전 연산", "file": "12주차/12주차_학습서.html", "anchor": "genetic-op", "summary": "비트 단위. 0↔1 뒤집기", "week": 12},
{"keyword": "배낭 문제", "english": "Knapsack Problem", "category": "문제", "file": "12주차/12주차_학습서.html", "anchor": "knapsack", "summary": "NP 문제. GA 응용", "week": 12},
{"keyword": "스키마 이론", "english": "Schema Theory", "category": "이론", "file": "12주차/12주차_학습서.html", "anchor": "randomness", "summary": "존 홀랜드. GA 효율성 입증", "week": 12},
{"keyword": "리처드 도킨스", "english": "Richard Dawkins", "category": "인물", "file": "12주차/12주차_학습서.html", "anchor": "randomness", "summary": "눈먼 시계공, 이기적 유전자", "week": 12},
{"keyword": "페이스 프린트", "english": "Face Print", "category": "응용", "file": "12주차/12주차_학습서.html", "anchor": "evolution", "summary": "GA로 몽타주 진화", "week": 12}
];
